### ISSUE TITLE
add apple-app-site-association file (question)

### ISSUE THREAD

**Issue by knolga** [vineetchoudhary/iOS-Universal-Links#1]
Hello, All
I'm testing universal links. For this task I create a site on gitHub and now I have problems with adding apple-app-site-association file.
Comparing with your project I saw that my file doesn't work in root path:
https://<user>.github.io/apple-app-site-association 
Can you advise how you added file to your repo? Did you set special settings after/before upload file?
Thanks for advance

**Comment by vineetchoudhary** [comment]
create a repo with name `knolga.github.io` and put `apple-app-site-association` in this repo.
